### PR TITLE
feat(network): update network crd

### PR DESCRIPTION
**Pull request by angao**
(cherry picked from commit 1cb90257f72d99bfa67dc942f6e2c435c58d1d62)

**What type of PR is this?**
/kind feature
/area network

**What this PR does / why we need it**:

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @hanxueluo @WangMinjie114 

**Does this PR introduce a user-facing change?**:

```release-note
Update Network CRD.
```

### CODE REVIEW

**Review by bbbmj — COMMENTED** [review]
/lgtm

**Comment by hanxueluo** [comment]
为什么代码合入后。commit 的 title 都变成了这种格式：“ update network crd (#32)”。 “feat(network): ” 没了。

@bbbmj

**Pull request merged**
