### PR TITLE
feat(network): export default network params

### PR DESCRIPTION
**Pull request by angao**
**What type of PR is this?**
/kind feature
/area network

**What this PR does / why we need it**:
- 暴露集群部署时默认网络参数

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @hanxueluo @WangMinjie114 

**Does this PR introduce a user-facing change?**:

```release-note
Export default network params.
```

### CODE REVIEW

**Comment by angao** [comment]
/hold
waiting to test

**Comment by WangMinjie114** [comment]
LGTM

**Review by bbbmj — COMMENTED** [review]
/lgtm

**Pull request merged**
