### PR TITLE
feat(*): Support gpu enhancement cluster

### PR DESCRIPTION
**Pull request by WangMinjie114**
**What type of PR is this?**
/kind feature
/area release

**What this PR does / why we need it**:
支持增强版集群

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @bbbmj @cbsfly @liwandaniel 

**Does this PR introduce a user-facing change?**:

```release-note
Support gpu enhancement cluster
```

### CODE REVIEW

**Review by bbbmj — COMMENTED** [review]
/lgtm

**Comment by bbbmj** [comment]
/hold

please fix the conflict

**Comment by WangMinjie114** [comment]
/hold cancel
conflict fixed

**Pull request merged**
